config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :draftees
  resources :users

  post 'draftees/:id/draft' => 'draftees#draft', as: :draft
  post 'draftees/:id/undraft' => 'draftees#undraft', as: :undraft

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/draftee.rb
class Draftee < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :fan_name
  validates_presence_of :img_url
  validates_presence_of :fav_team
  validates_presence_of :why_draft_me
  validates_presence_of :fav_bose_product
  validates_presence_of :fan_score

  def draft(user_id)
    self.drafted = true
    self.user_id = user_id
    self.save
  end

  def undraft
    self.drafted = false
    self.user_id = nil
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  has_many :draftees

 def admin?
  admin == true
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end

  def no_route_redirect
    flash[:alert] = "That is not a valid page."
    redirect_to root_path
  end

  private

  def require_user_signed_in
    unless user_signed_in?

      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/draftees_controller.rb
class DrafteesController < ApplicationController
  before_filter :require_user_signed_in, only: [:new, :show, :edit, :create, :update, :destroy]
  before_action :set_draftee, only: [:show, :draft, :undraft, :edit, :update, :destroy]

  def index
    @draftees = Draftee.all
  end

  def show
  end

  def new
    @draftee = Draftee.new
  end

  def edit
  end

  def draft
    if !@draftee.drafted
      @draftee.draft(params[:user_id])
    else
      flash[:alert] = "already drafted"
    end
      redirect_to draftees_path
  end

  def undraft
    @draftee.drafted && @draftee.user_id == params[:user_id]
    @draftee.undraft
    redirect_to draftees_path
  end

  def create
    @draftee = Draftee.new(draftee_params)
    @draftee.user = current_user

    respond_to do |format|
      if @draftee.save
        format.html { redirect_to @draftee, notice: 'Draftee was successfully created.' }
        format.json { render :show, status: :created, location: @draftee }
      else
        format.html { render :new }
        format.json { render json: @draftee.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @draftee.update(draftee_params)
        format.html { redirect_to @draftee, notice: 'Draftee was successfully updated.' }
        format.json { render :show, status: :ok, location: @draftee }
      else
        format.html { render :edit }
        format.json { render json: @draftee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @draftee.destroy
    respond_to do |format|
      format.html { redirect_to draftees_url, notice: 'Draftee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_draftee
      @draftee = Draftee.find(params[:id])
    end

    def draftee_params
      params.require(:draftee).permit(:id, :fan_name, :img_url, :fav_team, :why_draft_me, :fav_bose_product, :user_id, :fan_score, :drafted)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/draftees_helper.rb
module DrafteesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/draftees/_form.html.erb
<%= form_for @draftee, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :fan_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fan_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :img_url, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :img_url, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fav_team, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fav_team, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :why_draft_me, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :why_draft_me, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fav_bose_product, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fav_bose_product, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fan_score, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :fan_score, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  draftees_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/draftees/edit.html.erb
<%- model_class = Draftee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Draftee %></h1>
</div>
<%= render :partial => 'form' %>

app/views/draftees/index.html.erb
<nav class="navbar navbar-default" role="navigation">
        <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand navbar-brand-centered">Bose Fantasy Draft</div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-brand-centered">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><a href="#">About</a></li>
          </ul>
          <% if current_user && current_user.admin? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Add New Draftee", new_draftee_path %></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>           
          </ul>
          <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
<div class="container">     
    <div class="span12">      
        <% if current_user %>
          <hr>
            <h3>Hi there, <%= current_user.name %>. You have currently drafted 
            <%= pluralize(current_user.draftees.count, "Players") %>.</h3>
          <hr>
        <% end %>
        <hr>
    </div> 
</div>

<div>
<% @draftees.each do |draftee| %>
<div class="container">
    <div class="row">
      <div class="[ col-sm-6 col-md-offset-2 col-md-4 ]">
        <div class="[ info-card ]">
            <%= image_tag(draftee.img_url, :style => "width: 100%") %>
          <div class="[ info-card-details ] animate">
            <div class="[ info-card-header ]">
              <h1><%= draftee.fan_name %></h1>
              <p><strong>Fan Score:</strong></p>
              <p><%= draftee.fan_score %></p>
              <p><strong>Favorite NFL Team:</strong></p>
              <p><%= draftee.fav_team %></p>
              <p><strong>Favorite Bose Product:</strong></p>
              <p><%= draftee.fav_bose_product %></p>
              <p><strong>Why Draft Me?</strong></p>
              <p><%= draftee.why_draft_me %></p>
            </div>
            <div class="[ info-card-detail ]">
              <!-- Description -->  
              <% if current_user %>
          <% if draftee.drafted && draftee.user_id == current_user.id %>
            <%= link_to "Undraft!", undraft_path(id:draftee.id, user_id:current_user.id), class: "btn btn-danger btn-lg", method: :post %> 
          <% elsif !draftee.drafted %>
           <%= link_to "Draft!", draft_path(id:draftee.id, user_id:current_user.id), class: "btn btn-primary btn-lg", method: :post%>
          <% else %>
          <p>Drafted by <strong><%= draftee.user.name %></strong></p>
          <% end %>
          <% if current_user.admin? %>
          <div>
            <br>
          <%= link_to '<i class="fa fa-trash-o fa-2x"></i>'.html_safe, draftee_path(draftee), method: :delete, data: { confirm: "Are you sure you want to delete this draftee?"} %>
          <%= link_to '<i class="fa fa-pencil-square-o fa-2x"></i>'.html_safe, edit_draftee_path(draftee) %>
          <% end %>
        </div>
        <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>    
<hr>

app/views/draftees/new.html.erb
<%- model_class = Draftee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Draftee %></h1>
</div>
<%= render :partial => 'form' %>

app/views/draftees/original_index.html.erb
<%- model_class = Draftee -%>
<div class="page-header">
  <h1><%=t '.title', :default => Draftee %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:fan_name) %></th>
      <th><%= model_class.human_attribute_name(:img_url) %></th>
      <th><%= model_class.human_attribute_name(:fav_team) %></th>
      <th><%= model_class.human_attribute_name(:why_draft_me) %></th>
      <th><%= model_class.human_attribute_name(:fav_bose_product) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:fan_score) %></th>
      <th><%= model_class.human_attribute_name(:drafted) %></th>


      <% if false %>
      <!-- <th><%= model_class.human_attribute_name(:created_at) %></th> -->
      <!-- <th><%=t '.actions', :default => t("helpers.actions") %></th> -->
      <% end %>

    </tr>
  </thead>
  <tbody>
    <% @draftees.each do |draftee| %>
      <tr>
        <td><%= draftee.id %></td>
        <td><%= draftee.fan_name %></td>
        <td><%= image_tag(draftee.img_url) %></td>
        <td><%= draftee.fav_team %></td>
        <td><%= draftee.why_draft_me %></td>
        <td><%= draftee.fav_bose_product %></td>
        <td><%= draftee.user_id %></td>
        <td><%= draftee.fan_score %></td>
        <% if current_user %>

          <% if draftee.drafted && draftee.user_id == current_user.id %>
            <td><%= link_to "Undraft", undraft_path(id:draftee.id, user_id:current_user.id) %></td>
          <% elsif !draftee.drafted %>
            <td><%= link_to "Draft", draft_path(id:draftee.id, user_id:current_user.id) %></td>
          <% else %>
          <td><p>Drafted</p></td>
          <% end %>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user && current_user.admin? %>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_draftee_path, :class => 'btn btn-primary' %>
<% end %>

app/views/draftees/show.html.erb
<%- model_class = Draftee -%>
<div class="page-header">
  <h1><%=t '.title', :default => Draftee %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fan_name) %></dt>
      <dd><pre class="prettyprint"><%= @draftee.fan_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:img_url) %></dt>
      <dd><pre class="prettyprint"><%= @draftee.img_url %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fav_team) %></dt>
      <dd><pre class="prettyprint"><%= @draftee.fav_team %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:why_draft_me) %></dt>
      <dd><pre class="prettyprint"><%= @draftee.why_draft_me %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fav_bose_product) %></dt>
      <dd><pre class="prettyprint"><%= @draftee.fav_bose_product %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:user_id) %></dt>
      <dd><pre class="prettyprint"><%= @draftee.user_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fan_score) %></dt>
      <dd><pre class="prettyprint"><%= @draftee.fan_score %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              draftees_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_draftee_path(@draftee), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              draftee_path(@draftee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>

        <% if false %>
          <!--
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          -->
        <% end %>

        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantasydraft</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/pages/index2.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/index_c.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bose | NLF</title>

  </head>

  <body>

    <!-- background image overlay (semi transparent dark background image overlay) -->
    <!-- comment or remove if you don't want the overlay on top of the image -->
    <div class="background-image-overlay"></div>

    <!-- outer background container - the element from where the default page background image is set, and the element which changes its background when scrolling through other sections (.section-wrapoer) that have attribute "data-custom-background-img" set. 
     - data-default-background-img attr is required for sections (.section-wrapper) below that have no custom background defined.
     - use same image in the backstretch.js code in the footer for IE8 or less browsers -->
    <div id="outer-background-container" data-default-background-img="assets/images/bg5.jpg" style="background-image:url(http://stephenmuscat.com/twilli_air/1.1/assets/images/other_images/bg5.jpg);"></div>
    <!-- end: #outer-background-container -->    

    <!-- Outer Container -->
    <div id="outer-container">

      <!-- Left Sidebar -->
      <section id="left-sidebar">
        <div class="logo">
          <%= image_tag("bose.png") %>
        </div>
        <div id="mobile-menu-icon" class="visible-xs" onClick="toggle_main_menu();"><span class="glyphicon glyphicon-th"></span></div>

        <ul id="main-menu">
          <li id="menu-item-alt-page" class="menu-item"><%= link_to "Draftees", draftees_path %></li>
          <li id="menu-item-alt-page" class="menu-item"><%= link_to "Leaderboard", draftees_path %></li>
          <li id="menu-item-featured" class="menu-item scroll"><a href="#featured">Featured</a></li>
          <li id="menu-item-contact" class="menu-item scroll"><a href="#contact">Contact</a></li>
          <!-- to include a link which doesn't scroll to a section inside the page, remove the .scroll class from the <li> - example below -->
          <!-- <li id="menu-item-alt-page" class="menu-item"><a href="http://www.link.com">Outer Link</a></li> -->
        </ul><!-- #main-menu -->
        <!-- ==================== END: MAIN MENU ==================== -->

      </section><!-- #left-sidebar -->
      <!-- end: Left Sidebar -->

      <!-- ==================================================================
      MAIN CONTENT
      ==================================================================  -->
      <!-- all the website sections are contained in the <article> tag with class ".section-wrapper" and a unique id.
           - to edit / remove / create website sections, you have to handle the content contained in these <article> tags -->
      <section id="main-content" class="clearfix">
        
        <!-- ==================== SECTION TYPE: Intro Text ==================== -->
        <!-- This type of section should contain heading and intro paragraph. It can also include links to other sections -->
        <!-- FOR EACH SECTION <article class="section-wrapper".. :
             - remember to use a unique id, 
             - (optional) set a "data-custom-background-img" attribute with a link to custom background image which will be used when the viewer scrolls to this section -->
        <article id="intro" class="section-wrapper clearfix" data-custom-background-img="assets/images/other_images/bg5.jpg">
          <div class="content-wrapper clearfix">
            <div class="col-sm-10 col-md-9 pull-right">

              <!-- Start: Section content to edit -->

                <!-- <p> text in .feature-text is larger  -->
                <section class="feature-text">
                  <h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit</h1>
                  <p>Etiam at ligula sit amet arcu laoreet consequat. Duis dictum lorem metus, vitae dapibus risus imperdiet nec. Suspendisse molestie lorem odio, sit amet. </p>
                  <!-- to add scrolling effects to links linking to same page section, add .link-scroll class -->
                  
                  <%= link_to "See The Fans!", draftees_path, :class => "link-scroll btn btn-outline-inverse btn-lg" %>
                </section>

              <!-- End: Section content to edit -->

            </div><!-- .col-sm-10 -->
          </div><!-- .content-wrapper -->
        </article><!-- .section-wrapper -->
        

      <!-- Footer -->
      <section id="footer">

        <!-- Go to Top -->
        <div id="go-to-top" onclick="scroll_to_top();"><span class="icon glyphicon glyphicon-chevron-up"></span></div>

        <!-- ==================================================================
        SOCIAL ICONS
        ==================================================================  -->
        <!-- Each social icon item consists of the following:
             - Link to the social page in href of <a>
             - social icon in the <img> - a list of social icons options are found in the directory assets/images/theme_images/social_icons/ -->
        <ul class="social-icons">
          <li><%= image_tag("twitter.png") %></li>
          <li><%= image_tag("facebook.png") %></li>
          <li><%= image_tag("googleplus.png") %></li>
        </ul>
        <!-- ==================== END: Social Icons ==================== -->

        <!-- copyright text -->
        <div class="footer-text-line">&copy; 2014 Bose | NFL</div>
      </section>
      <!-- end: Footer -->      

    </div><!-- #outer-container -->
    <!-- end: Outer Container -->

    <!-- Modal -->
    <!-- DO NOT MOVE, EDIT OR REMOVE - this is needed in order for popup content to be populated in it -->
    <div class="modal fade" id="common-modal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <div class="modal-body">
          </div><!-- .modal-body -->
        </div><!-- .modal-content -->
      </div><!-- .modal-dialog -->
    </div><!-- .modal -->    

    <!-- Javascripts
    ================================================== -->

    <!-- Jquery and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>

    <!-- Easing - for transitions and effects -->
    <script src="assets/js/jquery.easing.1.3.js"></script>

    <!-- background image strech script -->
    <script src="assets/js/jquery.backstretch.min.js"></script>
    <!-- background image fix for IE 9 or less
       - use same background as set above to <body> -->
    <!--[if lt IE 9]>
    <script type="text/javascript">
    $(document).ready(function(){
      jQuery("#outer-background-container").backstretch("assets/images/other_images/bg5.jpg");
    });
    </script> 
    <![endif]-->  

    <!-- detect mobile browsers -->
    <script src="assets/js/detectmobilebrowser.js"></script>

    <!-- owl carousel js -->
    <script src="assets/js/owl-carousel/owl.carousel.min.js"></script>

    <!-- Custom functions for this theme -->
    <script src="assets/js/functions.js"></script>
    <script src="assets/js/initialise-functions.js"></script>

    <!-- IE9 form fields placeholder fix -->
    <!--[if lt IE 9]>
    <script>contact_form_IE9_placeholder_fix();</script>
    <![endif]-->  

  </body>
</html>